server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Evitando erro 404
        try_files $uri $uri/ /index.html;
    }

    # Ignorar logs de favicon para não poluir o sistema.
    location = /favicon.ico { log_not_found off; access_log off; }
}
